### ISSUE TITLE
cimgui and imgui version don't match?

### ISSUE THREAD

**Issue by itmuckel** [SpexGuy/Zig-ImGui#1]
Before I try to explain, see this issue: https://github.com/cimgui/cimgui/issues/168#issuecomment-737841633

I updated to latest cimgui, but now I'm getting:
```
generate.py", line 707, in <module>
    with open(TEMPLATES_JSON_FILE) as f:
IOError: [Errno 2] No such file or directory: 'cimgui/generator/output/templates.json'
```

with `build_all.bat`.

**Comment by SpexGuy** [comment]
Ah, sorry, this was the result of a half-done upgrade that I accidentally pushed to the repo.  I've removed the offending commit so master branch should build now.  There are still a few known issues that we talked about on Discord (#2, #3, and in the vulkan header [#1](https://github.com/SpexGuy/Zig-Vulkan-Headers/issues/1) and [#2](https://github.com/SpexGuy/Zig-Vulkan-Headers/issues/2)), but I think this one can be closed.
