### ISSUE TITLE
Examples don't compile with Zig 0.7.0

### ISSUE THREAD

**Issue by SpexGuy** [SpexGuy/Zig-ImGui#3]
They are using a dialect of Zig that is very close to 0.7.0 but slightly before.  Notable changes are the introduction of `opaque` as a keyword and the change from `TypeInfo.Int.is_signed` to `TypeInfo.Int.signedness`.

**Comment by CuriouserThing** [comment]
Additionally `inline` -> `callconv(.Inline)`, which `zig fmt` does process.

**Comment by SpexGuy** [comment]
Closed by 36c78ae, compiles with 0.9.0.
